Repository SesacBest/best-calendar-web, pull requests merged in 2025-03, with the labels that each got.

#46 BCW 25-[BE] 할일 API 구현
  be/src/main/java/com/ssb/scalendar/domain/task/controller/TaskController.java
  be/src/main/java/com/ssb/scalendar/domain/task/dto/request/CheckTaskRequestDto.java
  be/src/main/java/com/ssb/scalendar/domain/task/dto/request/TaskCreateRequestDto.java
  be/src/main/java/com/ssb/scalendar/domain/task/dto/response/CheckTaskResponseDto.java
  be/src/main/java/com/ssb/scalendar/domain/task/dto/response/MonthlyTaskResponseDto.java
  be/src/main/java/com/ssb/scalendar/domain/task/dto/response/TaskResponseDto.java
  be/src/main/java/com/ssb/scalendar/domain/task/entity/Task.java
  be/src/main/java/com/ssb/scalendar/domain/task/repository/TaskRepository.java
  be/src/main/java/com/ssb/scalendar/domain/task/service/TaskService.java
Labels: feat

#48 BCW-61 [FE] 소셜 로그인 페이지 생성
  fe/.env.example
  fe/src/api/authApi.js
  fe/src/components/SocialLogin.jsx
  fe/src/images/kakao_login_large_wide.png
  fe/src/pages/KakaoRedirect.jsx
  fe/src/pages/Login.jsx
  fe/src/router/index.jsx
Labels: feat

#49 BCW-21 [FE] 할일 조회 페이지 생성
  fe/src/api/TaskApi.js
  fe/src/api/scheduleApi.js
  fe/src/components/day/Schedule.jsx
  fe/src/components/day/ScheduleCreate.jsx
  fe/src/components/day/Task.jsx
  fe/src/components/day/TaskCreate.jsx
Labels: feat

#50 BCW-63 [BE] 일기 api 보완
  be/src/main/java/com/ssb/scalendar/domain/diary/entity/Diary.java
  be/src/main/java/com/ssb/scalendar/domain/diary/service/DiaryService.java
  be/src/main/java/com/ssb/scalendar/global/exception/GlobalExceptionHandler.java
Labels: fix

#51 BCW-22 [FE] 일기 조회, 수정 페이지 생성
  fe/package-lock.json
  fe/package.json
  fe/src/api/diaryApi.js
  fe/src/components/DayHeader.jsx
  fe/src/components/day/Diary.jsx
  fe/src/components/day/DiaryCreate.jsx
  fe/src/components/day/diary/DiaryEditor.jsx
  fe/src/components/day/diary/DiaryForm.jsx
  fe/src/components/day/diary/EditorToolbar.jsx
  fe/src/components/day/diary/styles/DiaryEditor.css
  fe/src/components/day/diary/styles/editorStyles.js
  fe/src/pages/Day.jsx
  fe/src/router/index.jsx
Labels: refactor, feat

#52 BCW-19 [FE] 일정 생성 페이지 디자인 설정
  fe/src/App.css
  fe/src/components/day/ScheduleCreate.jsx
Labels: fix, feat

#53 BCW-23 [FE] 일기 수정 기능 구현
  be/src/main/java/com/ssb/scalendar/domain/diary/dto/request/DiaryUpdateRequestDto.java
  be/src/main/java/com/ssb/scalendar/domain/diary/entity/Diary.java
  fe/src/components/day/Diary.jsx
  fe/src/components/day/DiaryCreate.jsx
  fe/src/components/day/diary/styles/DiaryEditor.css
Labels: fix, feat

#54 BCW-65 [FE] 랜딩 페이지 세부사항 추가 및 수정
  fe/src/App.css
  fe/src/components/Footer.jsx
  fe/src/pages/Home.jsx
Labels: feat

#55 BCW-20 [FE] 일정 조회 페이지 및 할일 생성 페이지 디자인 설정
  fe/src/components/Footer.jsx
  fe/src/components/day/Schedule.jsx
  fe/src/components/day/ScheduleCreate.jsx
  fe/src/components/day/TaskCreate.jsx
  fe/src/index.css
  fe/src/pages/Day.jsx
Labels: feat

#57 BCW-66 [FE] 할 일 조회 페이지 디자인 설정
  fe/src/components/day/Schedule.jsx
  fe/src/components/day/ScheduleCreate.jsx
  fe/src/components/day/Task.jsx
  fe/src/components/day/TaskCreate.jsx
  fe/src/index.css
Labels: feat

#59 BCW-68 [FE] 일정, 조회 글자 수 제한 추가 및 디자인 설정
  fe/src/components/day/ScheduleCreate.jsx
  fe/src/components/day/Task.jsx
  fe/src/components/day/TaskCreate.jsx
  fe/src/index.css
Labels: feat

#58 BCW-67 [BE] 일정 생성 글자 수 제한 추가
  be/src/main/java/com/ssb/scalendar/domain/schedule/dto/request/ScheduleCreateRequestDto.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/entity/Schedule.java
  be/src/main/java/com/ssb/scalendar/global/exception/GlobalExceptionHandler.java
Labels: fix, feat

#60 BCW-69 [FE] 랜딩 페이지 추가 세부사항 수정 및 이동 히스토리 제거
  fe/src/components/Footer.jsx
  fe/src/components/Header.jsx
  fe/src/pages/Home.jsx
Labels: fix, feat

#56 BCW-62 [FE] 달력 세부 레이아웃 수정 및 편의성 향상
  fe/src/App.jsx
  fe/src/HistoryContainer.jsx
  fe/src/MyHistoryProvider.jsx
  fe/src/index.css
  fe/src/pages/Calendar.jsx
  fe/src/pages/CalendarModalContent.jsx
  fe/src/router/index.jsx
Labels: fix, feat

#63 BCW-73 [FE] day 페이지 디자인 설정 및 비로그인 접근 제한
  fe/src/components/Empty.jsx
  fe/src/components/day/Diary.jsx
  fe/src/components/day/Schedule.jsx
  fe/src/components/day/Task.jsx
  fe/src/pages/Day.jsx
Labels: feat

#64 BCW-71[FE] 할 일 입력 텍스트 길이 제한 설정 및 isComplete=fasle 설정
  be/src/main/java/com/ssb/scalendar/domain/task/dto/request/TaskCreateRequestDto.java
  be/src/main/java/com/ssb/scalendar/domain/task/entity/Task.java
Labels: fix, feat

#66 BCW-77-[FE] 할 일 DTO 수정
  be/src/main/java/com/ssb/scalendar/domain/task/dto/response/MonthlyTaskResponseDto.java
Labels: fix

#68 BCW-64 [FE/BE] 소셜 로그인 기능 구현 완성
  .env.example
  .github/workflows/deploy.yml
  be/build.gradle
  be/src/main/java/com/ssb/scalendar/domain/user/controller/AuthController.java
  be/src/main/java/com/ssb/scalendar/domain/user/entity/User.java
  be/src/main/java/com/ssb/scalendar/domain/user/repository/UserRepository.java
  be/src/main/java/com/ssb/scalendar/global/config/SecurityConfig.java
  be/src/main/java/com/ssb/scalendar/kakao/CustomOAuth2User.java
  be/src/main/java/com/ssb/scalendar/kakao/CustomOAuth2UserService.java
  be/src/main/java/com/ssb/scalendar/kakao/KakaoUserInfo.java
  be/src/main/java/com/ssb/scalendar/kakao/OAuth2SuccessHandler.java
  be/src/main/java/com/ssb/scalendar/kakao/OAuth2UserInfo.java
  be/src/main/resources/application.properties
  fe/.env.example
  fe/src/api/authApi.js
  fe/src/components/SocialLogin.jsx
  fe/src/pages/KakaoRedirect.jsx
  fe/src/router/index.jsx
  fe/src/store/slices/authSlice.js
Labels: feat, chore

#70 BCW-[FE] 일기 수정 기능 오류 수정(+ 일정 생성 페이지 수정)
  fe/src/components/day/DiaryCreate.jsx
  fe/src/components/day/ScheduleCreate.jsx
Labels: fix

#73 Update README.md
  README.md
Labels: docs

#74 BCW-81 [DP] 환경변수 설정 변경
  .env.example
  .github/workflows/deploy.yml
  be/.env.example
  be/src/main/resources/application.properties
  docker-compose.yml
Labels: chore

#75 BCW-82 [DP] 환경변수 설정 오류 해결
  .github/workflows/deploy.yml
Labels: fix

#76 BCW-83 [DP] 카카오 소셜 로그인 오류 해결
  .github/workflows/deploy.yml
  be/.env.example
  be/src/main/resources/application.properties
  fe/.env.example
  fe/src/components/SocialLogin.jsx
  fe/src/images/kakao_login_large_wide.png
Labels: fix

#77 BCW-83 [DP] 카카오 소셜 로그인 오류 해결
  .env.example
  .github/workflows/deploy.yml
  docker-compose.yml
  fe/.env.example
  fe/Dockerfile
  fe/src/api/TaskApi.js
  fe/src/components/Header.jsx
  fe/src/components/SocialLogin.jsx
  fe/src/components/day/ScheduleCreate.jsx
  fe/src/components/day/TaskCreate.jsx
  fe/src/pages/KakaoRedirect.jsx
  fe/src/pages/Login.jsx
  fe/src/pages/Signup.jsx
Labels: fix

#78 Update README.md
  README.md
Labels: docs
