Repository SesacBest/best-calendar-web, pull requests merged in 2025-02, with the labels that each got.

#2 BCW-3 프론트엔드 환경 설정
  be/.env.example
  be/.gitattributes
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/ssb/scalendar/ScalendarApplication.java
  be/src/main/resources/application.properties
  be/src/test/java/com/ssb/scalendar/ScalendarApplicationTests.java
  fe/.gitignore
  fe/README.md
  fe/eslint.config.js
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/public/vite.svg
  fe/src/App.css
  fe/src/App.jsx
  fe/src/assets/react.svg
  fe/src/index.css
  fe/src/main.jsx
  fe/vite.config.js
Labels: chore

#4 BCW-3 프론트엔드 환경 설정
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/src/App.jsx
Labels: chore

#5 feature/BCW-27-be-folder-structure-design
  be/src/main/java/com/ssb/scalendar/domain/user/controller/AuthController.java
  be/src/main/java/com/ssb/scalendar/domain/user/dto/request/UserRequestDto.java
  be/src/main/java/com/ssb/scalendar/domain/user/dto/response/UserResponseDto.java
  be/src/main/java/com/ssb/scalendar/domain/user/entity/User.java
  be/src/main/java/com/ssb/scalendar/domain/user/repository/UserRepository.java
  be/src/main/java/com/ssb/scalendar/domain/user/service/UserService.java
  be/src/main/java/com/ssb/scalendar/global/config/tmpfiles
  be/src/main/java/com/ssb/scalendar/global/entity/tmpfiles
  be/src/main/java/com/ssb/scalendar/global/exception/tmpfiles
  be/src/main/java/com/ssb/scalendar/global/response/tmpfiles
  be/src/main/java/com/ssb/scalendar/global/security/handler/tmpfiles
  be/src/main/java/com/ssb/scalendar/global/security/jwt/tmpfiles
Labels: chore

#6 BCW-10 [FE] 랜딩 페이지 생성
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/App.css
  fe/src/App.jsx
  fe/src/RootLayout.jsx
  fe/src/api/axios.js
  fe/src/components/Footer.jsx
  fe/src/components/Header.jsx
  fe/src/index.css
  fe/src/pages/Calendar.jsx
  fe/src/pages/Day.jsx
  fe/src/pages/Home.jsx
  fe/src/pages/Login.jsx
  fe/src/pages/Signup.jsx
  fe/src/router/index.jsx
  fe/src/store/slices/tmp
  fe/src/store/store.js
  fe/vite.config.js
Labels: feat, chore

#8 BCW-29 [FE] header, footer component 위치 변경 및 환경변수 예시 생성
  .env.example
  be/.env.example
  fe/.env.example
  fe/src/RootLayout.jsx
  fe/src/components/Footer.jsx
  fe/src/pages/Home.jsx
  fe/src/router/index.jsx
Labels: fix, chore

#10 BCW-14 [BE] 로그인 API 구현
  be/src/main/java/com/ssb/scalendar/domain/user/controller/AuthController.java
  be/src/main/java/com/ssb/scalendar/domain/user/controller/TestController.java
  be/src/main/java/com/ssb/scalendar/domain/user/dto/request/LoginRequestDto.java
  be/src/main/java/com/ssb/scalendar/domain/user/dto/response/LoginResponseDto.java
  be/src/main/java/com/ssb/scalendar/domain/user/repository/UserRepository.java
  be/src/main/java/com/ssb/scalendar/domain/user/service/AuthService.java
  be/src/main/java/com/ssb/scalendar/global/config/SecurityConfig.java
  be/src/main/java/com/ssb/scalendar/global/exception/GlobalExceptionHandler.java
  be/src/main/java/com/ssb/scalendar/global/security/CustomUserDetailsService.java
  be/src/main/java/com/ssb/scalendar/global/security/handler/CustomAccessDeniedHandler.java
  be/src/main/java/com/ssb/scalendar/global/security/handler/JwtAuthenticationEntryPoint.java
  be/src/main/java/com/ssb/scalendar/global/security/handler/tmpfiles
  be/src/main/java/com/ssb/scalendar/global/security/jwt/JwtAuthenticationFilter.java
  be/src/main/java/com/ssb/scalendar/global/security/jwt/JwtTokenProvider.java
  be/src/main/java/com/ssb/scalendar/global/security/jwt/tmpfiles
  be/src/main/resources/application.properties
Labels: fix, feat

#14 BCW-30 [BE] 로그인 API 구현 수정
  be/.env.example
  be/src/main/java/com/ssb/scalendar/domain/user/controller/AuthController.java
  be/src/main/java/com/ssb/scalendar/domain/user/controller/TestController.java
  be/src/main/java/com/ssb/scalendar/global/config/SecurityConfig.java
  be/src/main/java/com/ssb/scalendar/global/security/CustomUserDetailsService.java
  be/src/main/java/com/ssb/scalendar/global/security/jwt/JwtTokenProvider.java
  be/src/main/resources/application.properties
Labels: fix

#15 BCW-11 [FE] 회원가입 페이지 생성
  fe/src/RootLayout.jsx
  fe/src/api/authApi.js
  fe/src/api/axios.js
  fe/src/index.css
  fe/src/pages/Signup.jsx
Labels: fix, feat, chore

#17 BCW-31 [FE] 로그인 페이지 생성 수정
  fe/src/App.jsx
  fe/src/AuthProvider.jsx
  fe/src/RootLayout.jsx
  fe/src/pages/Login.jsx
Labels: fix, refactor

#16 BCW-32 [BE] email 중복 체크 API 구현
  be/src/main/java/com/ssb/scalendar/domain/user/controller/AuthController.java
  be/src/main/java/com/ssb/scalendar/domain/user/dto/response/SignupResponseDto.java
  be/src/main/java/com/ssb/scalendar/domain/user/service/AuthService.java
  be/src/main/java/com/ssb/scalendar/global/exception/GlobalExceptionHandler.java
Labels: fix, refactor, feat

#18 BCW-33 [FE] 회원가입 - 이메일 중복체크, 비밀번호 확인 기능
  fe/src/api/authApi.js
  fe/src/pages/Signup.jsx
Labels: refactor, feat

#20 BCW-36 [DP] 1차 배포
  .env.example
  .github/workflows/deploy.yml
  be/.env.example
  be/Dockerfile
  be/docker-compose-db.yml
  be/gradle.properties
  docker-compose.yml
  fe/Dockerfile
  fe/nginx.conf
  fe/package-lock.json
  fe/package.json
  fe/src/api/axios.js
  fe/vite.config.js
Labels: chore

#21 BCW-37 [DP] 1차 배포 수정 - 1
  .github/workflows/deploy.yml
Labels: fix

#22 BCW-38 [DP] 1차 배포 수정 - 2
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: chore

#23 BCW-39 HTTPS 적용
  docker-compose.yml
  fe/nginx.conf
Labels: chore

#24 BCW-40 [DP] Nginx에 환경변수 적용
  .env.example
  .github/workflows/deploy.yml
  fe/nginx.conf
  fe/templates/default.conf.template
  fe/templates/https.conf.template
Labels: chore

#25 BCW-41 [DP] Nginx에 환경변수 적용2
  .env.example
  fe/Dockerfile
Labels: fix

#26 BCW-43 [DP] Nginx에 환경변수 적용3
  docker-compose.yml
  fe/.env.example
Labels: fix

#28 BCW-45 [DP] CORS origin 추가
  .env.example
  be/src/main/java/com/ssb/scalendar/global/config/SecurityConfig.java
  be/src/main/resources/application.properties
  fe/Dockerfile
Labels: fix

#29 BCW-46 [DP] CORS origin 수정 1
  be/src/main/java/com/ssb/scalendar/global/config/SecurityConfig.java
Labels: fix

#30 BCW-47 [DP] CORS origin 수정 2
  .env.example
  .github/workflows/deploy.yml
Labels: fix

#32 BCW-15 [FE] 달력 페이지 생성
  fe/package-lock.json
  fe/package.json
  fe/src/pages/Calendar.jsx
Labels: feat

#33 BCW-51 [FE] 회원가입 유효성 문구 수정 및 이동 수정
  fe/src/pages/Signup.jsx
Labels: fix

#34 BCW-50 [FE] 헤더 리팩토링 및 로그인 유무에 따른 기능 추가
  fe/src/components/Header.jsx
Labels: fix, feat

#35 BCW-53 [FE] Header component의 빠진 이동 로직 추가
  fe/src/components/Header.jsx
Labels: feat

#36 BCW-54 [FE] Header component의 빠진 이동 로직 추가 2
  fe/src/components/Header.jsx
  fe/src/pages/Signup.jsx
Labels: fix, refactor, feat

#38 BCW-24 [BE] 일정 API 구현
  be/src/main/java/com/ssb/scalendar/domain/schedule/controller/ScheduleController.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/dto/request/ScheduleCreateRequestDto.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/dto/response/MonthlyScheduleResponseDto.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/dto/response/ScheduleResponseDto.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/entity/Schedule.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/repository/DailyCount.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/repository/ScheduleRepository.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/service/ScheduleService.java
Labels: feat

#39 BCW-18 [FE] 일정 관련 및 할일 추가 페이지 생성
  fe/src/api/TaskApi.js
  fe/src/api/scheduleApi.js
  fe/src/components/Empty.jsx
  fe/src/components/Header.jsx
  fe/src/components/day/DiaryCreate.jsx
  fe/src/components/day/Schedule.jsx
  fe/src/components/day/ScheduleCreate.jsx
  fe/src/components/day/Task.jsx
  fe/src/components/day/TaskCreate.jsx
  fe/src/index.css
  fe/src/pages/Login.jsx
  fe/src/router/index.jsx
Labels: feat

#41 BCW-57 [BE] 일정 조회 by day API 보완
  be/src/main/java/com/ssb/scalendar/domain/common/projection/DailyCount.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/controller/ScheduleController.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/dto/response/MonthlyScheduleResponseDto.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/repository/ScheduleRepository.java
  be/src/main/java/com/ssb/scalendar/domain/schedule/service/ScheduleService.java
Labels: refactor, feat

#42 BCW-26 [BE] 일기 API 구현
  be/src/main/java/com/ssb/scalendar/domain/diary/controller/DiaryController.java
  be/src/main/java/com/ssb/scalendar/domain/diary/dto/request/DiaryCreateRequestDto.java
  be/src/main/java/com/ssb/scalendar/domain/diary/dto/request/DiaryUpdateRequestDto.java
  be/src/main/java/com/ssb/scalendar/domain/diary/dto/response/DiaryResponseDto.java
  be/src/main/java/com/ssb/scalendar/domain/diary/entity/Diary.java
  be/src/main/java/com/ssb/scalendar/domain/diary/repository/DiaryRepository.java
  be/src/main/java/com/ssb/scalendar/domain/diary/service/DiaryService.java
  be/src/main/java/com/ssb/scalendar/global/response/ApiResponse.java
Labels: refactor, feat

#44 BCW-34 [FE] 로그인 페이지 - 레이아웃 배치 통일
  fe/src/pages/Login.jsx
  fe/src/pages/Signup.jsx
Labels: refactor
